# Build config
build:
  days: 2
  captures:
    - "C:/bramon/!data"
  stations:
    - TLP1
    - TLP2
  converter:
    path: "C:/bramon/tools/ffmpeg.exe"
  storage:
    url: "https://storage.meteoros.floripa.br/"
    captures: "D:/capturas"
    videos: "D:/capturas/videos"
  output:
    base: "C:/Users/thiago/Projetos/meteoros-floripa-site"